In [1]:
import numpy as np

# Scalar, Vector and Matrix

In [61]:
scalar=5
vector=np.array([5,-2,4])
vector2=np.array([2,3,4])
matrix=np.array([[5,-2,4],[4,2,3]])
matrix2=np.array([[1,3,5],[4,4,2]])

In [62]:
matrix.shape

(2, 3)

In [63]:
vector.shape

(3,)

In [64]:
vector.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [65]:
tensor=np.array([matrix,matrix2])

In [66]:
tensor.shape

(2, 2, 3)

In [67]:
tensor_manual=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [68]:
tensor_manual

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [69]:
tensor_manual.shape

(3, 2, 3)


# Subtraction and Addition

In [70]:
matrix+matrix2

array([[6, 1, 9],
       [8, 6, 5]])

In [71]:
matrix-matrix2

array([[ 4, -5, -1],
       [ 0, -2,  1]])

In [72]:
matrix+2

array([[7, 0, 6],
       [6, 4, 5]])

# Transposing Venctors

In [73]:
matrix

array([[ 5, -2,  4],
       [ 4,  2,  3]])

In [74]:
matrix.T

array([[ 5,  4],
       [-2,  2],
       [ 4,  3]])

In [75]:
vector

array([ 5, -2,  4])

In [76]:
vector.T

array([ 5, -2,  4])

# Dot  Product (Inter Product)

In [78]:
np.dot(vector,vector2)

20

In [81]:
np.dot(5,6)

30

In [82]:
np.dot(vector,10)

array([ 50, -20,  40])

In [83]:
vector*10

array([ 50, -20,  40])

In [86]:
matrix3=matrix2.reshape(3,2)

In [95]:
np.dot(matrix2,matrix3)

array([[36, 25],
       [32, 32]])